[tool.ruff]
line-length = 100
lint.select = ["E", "F", "B", "I", "N"]
lint.ignore = ["E501"]  # Довгі рядки, якщо потрібно дозволити
exclude = ["resources", "tests", ".venv"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
